import Product from '../models/Product.js';

const initialProducts = [
  {
    name: 'Modular Wardrobe',
    category: 'Wardrobes',
    price: 6299,
    image: '/images/wardrobe.png',
    description: 'Stylish modular wardrobe with sliding doors and built-in storage.',
    inStock: true,
  },
  {
    name: '10-Step Shoe Rack',
    category: 'Shoe Rack',
    price: 2199,
    image: '/images/shoe.png',
    description: 'Durable shoe rack with multiple tiers for easy organization.',
    inStock: true,
  },
  {
    name: 'Designer Kitchen Shelf',
    category: 'Kitchen',
    price: 2899,
    image: '/images/kitchen.png',
    description: 'Compact kitchen shelf perfect for spices and cookware storage.',
    inStock: true,
  },
  {
    name: 'Bathroom Essentials Rack',
    category: 'Bathroom Essentials',
    price: 1899,
    image: '/images/bathroom.png',
    description: 'Bathroom shelf organizer for towels, soaps, and accessories.',
    inStock: true,
  },
  {
    name: 'Bathroom Storage Trio',
    category: 'Bathroom Storage',
    price: 2399,
    image: '/images/bathroom1.png',
    description: 'Three-piece bathroom storage set for a tidy vanity.',
    inStock: true,
  },
  {
    name: 'Home Decor Organizer',
    category: 'Home Essentials',
    price: 1799,
    image: '/images/home.png',
    description: 'Multi-purpose organizer for home decor and small accessories.',
    inStock: true,
  },
  {
    name: 'Elephant Wall Mount',
    category: 'Wall Shelves',
    price: 1499,
    image: '/images/shelf.png',
    description: 'Decorative wall mount shelf shaped like an elephant.',
    inStock: true,
  },
  {
    name: 'Doll Wall Mount',
    category: 'Wall Shelves',
    price: 1499,
    image: '/images/shelf.png',
    description: 'Cute wall mount shelf for a cozy kids room display.',
    inStock: true,
  },
  {
    name: 'L Corner Shelf',
    category: 'Wall Shelves',
    price: 1799,
    image: '/images/shelf.png',
    description: 'L-shaped corner shelf to maximize wall space.',
    inStock: true,
  },
  {
    name: 'Organizer Caddy',
    category: 'Organizers',
    price: 1299,
    image: '/images/organizer.png',
    description: 'Portable organizer caddy for toiletries and stationery.',
    inStock: true,
  },
  {
    name: 'Storage Boxes Set',
    category: 'Storage Boxes',
    price: 1699,
    image: '/images/organizer1.png',
    description: 'Set of stackable storage boxes for closets and shelves.',
    inStock: true,
  },
  {
    name: 'Multi Organizer Tower',
    category: 'Multi Organizers',
    price: 1999,
    image: '/images/organizer2.png',
    description: 'Vertical organizer tower for efficient storage in small spaces.',
    inStock: true,
  },
  {
    name: 'Bathroom Corner Shelf',
    category: 'Bathroom Storage',
    price: 2099,
    image: '/images/bathroom2.png',
    description: 'Corner shelf designed for bathroom storage and decor.',
    inStock: true,
  },
  {
    name: '10 Step Black Shoe Rack',
    category: '10 Step Black',
    price: 2599,
    image: '/images/10%20STEP%20black/listings/1.png',
    description: 'Durable black 10-step shoe rack for entryway storage.',
    inStock: true,
  },
  {
    name: '10 Step White Shoe Rack',
    category: '10 Step White',
    price: 2699,
    image: '/images/10%20step%20white/listings/1.png',
    description: 'Clean white 10-step shoe rack with ample shoe storage.',
    inStock: true,
  },
  {
    name: '12 Step Black Shoe Rack',
    category: '12 Step Black',
    price: 2999,
    image: '/images/12%20step%20black/71eaHlAwHXL._SL1500_.jpg',
    description: 'Tall 12-step shoe rack for large collections of shoes.',
    inStock: true,
  },
  {
    name: '12 Step White Shoe Rack',
    category: '12 Step White',
    price: 3099,
    image: '/images/12%20step%20white/listings/1.png',
    description: 'White 12-step shoe rack with premium load-bearing shelves.',
    inStock: true,
  },
  {
    name: '4 Box Blue Wardrobe',
    category: '4 Box Blue',
    price: 5599,
    image: '/images/4%20BOX%20BLUE/1st%20image.png',
    description: 'Bright blue 4-box wardrobe designed for kids rooms.',
    inStock: true,
  },
  {
    name: '4 Box HK Pink Wardrobe',
    category: '4 Box HK Pink',
    price: 5799,
    image: '/images/4%20BOX%20HK%20PINK/1.png',
    description: 'Pink 4-box wardrobe with sturdy shelving and playful style.',
    inStock: true,
  },
  {
    name: '4 Box Pink Wardrobe',
    category: '4 Box Pink',
    price: 5699,
    image: '/images/4%20BOX%20PINK/1.png',
    description: 'Soft pink 4-box wardrobe with easy-access storage.',
    inStock: true,
  },
  {
    name: '8 Box Green Wardrobe',
    category: '8 Box Green',
    price: 6399,
    image: '/images/8%20B0X%20GREEN/1.png',
    description: 'Green 8-box wardrobe with abundant storage compartments.',
    inStock: true,
  },
  {
    name: '8 Box Animal Blue Wardrobe',
    category: '8 Box Animal Blue',
    price: 6499,
    image: '/images/8%20BOX%20ANIMAL%20BLUE/listings/1.png',
    description: 'Animal-print blue 8-box wardrobe for fun bedroom decor.',
    inStock: true,
  },
  {
    name: '8 Box Blue Wardrobe',
    category: '8 Box Blue',
    price: 6299,
    image: '/images/8%20BOX%20BLUE/1.png',
    description: 'Blue 8-box wardrobe for organized storage and styling.',
    inStock: true,
  },
  {
    name: '8 Box Cat Wardrobe',
    category: '8 Box Cat',
    price: 6399,
    image: '/images/8%20BOX%20CAT/listings/1.jpg',
    description: 'Cat-themed 8-box wardrobe with cute kids styling.',
    inStock: true,
  },
  {
    name: '8 Box HK Pink Wardrobe',
    category: '8 Box HK Pink',
    price: 6599,
    image: '/images/8%20BOX%20HK%20PINK/1.png',
    description: 'Hot pink 8-box wardrobe built for charming bedroom storage.',
    inStock: true,
  },
  {
    name: '8 Box Pink Wardrobe',
    category: '8 Box Pink',
    price: 6599,
    image: '/images/8%20BOX%20PINK/listings/1.png',
    description: 'Pink 8-box wardrobe with spacious storage and modern design.',
    inStock: true,
  },
  {
    name: 'Dollmount Shelf',
    category: 'Dollmount Shelf',
    price: 1799,
    image: '/images/dollmount%20shelf/product-jpeg-1000x1000.webp',
    description: 'Cute dollmount shelf perfect for kids room displays.',
    inStock: true,
  },
  {
    name: 'Elephant Mount Shelf',
    category: 'Elephant Mount',
    price: 1899,
    image: '/images/Elephant%20mount/plastic-elephant-shaped-storage-shelf-500x500.webp',
    description: 'Elephant-shaped wall mount shelf for playful decor.',
    inStock: true,
  },
];

const seedInitialProducts = async () => {
  const count = await Product.countDocuments();
  if (count === 0) {
    await Product.insertMany(initialProducts);
    console.log('Seeded initial products');
  }
};

export default seedInitialProducts;
